services:
  caddy:
    image: caddy:latest
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      CADDY_ADMIN: "0.0.0.0:2019"

  # ui:
  #   depends_on:
  #     - caddy
  #   links:
  #     - caddy
  #   build:
  #     context: .
  #   environment:
  #     CADDY_URL: http://caddy:2019
  #   ports:
  #     - "8081:8081"
