services:
  caddy:
    image: caddy:latest
    network_mode: host
    # ports:
    #   - "2019:2019"
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    environment:
      CADDY_ADMIN: "0.0.0.0:2019"
    # volumes:
    #   - ./caddy/conf:/etc/caddy

  # ui:
  #   depends_on:
  #     - caddy
  #   links:
  #     - caddy
  #   build:
  #     context: .
  #   environment:
  #     CADDY_URL: http://caddy:2019
  #   ports:
  #     - "3003:8081"
